@Woof.api = http://localhost:5088

Post {{Woof.api}}/workflows/create
Content-Type: application/json

{
  "name": "Crap"
}

###

Post {{Woof.api}}/runs
Content-Type: application/json

{
  "workflowId": "88560961-a703-4ae7-ad3e-b8e3125f3b4d"
}
