@Woof.api = http://localhost:5198

GET {{Woof.api}}/definitions

###
Post {{Woof.api}}/definitions/create
Content-Type: application/json

{
  "name": "Crap"
}

###

Post {{Woof.api}}/definitions/add_sequential
Content-Type: application/json

{
  "workflowId": "f4180512-7858-4fbb-a0e5-c7eceb1db7ca",
  "parentStepId": null,
  "step": {
    "name": "mult",
    "executableName": "Exec.Multiply.exe",
    "arguments": "1 2"
  }
}

###

Post {{Woof.api}}/definitions/add_loop
Content-Type: application/json

{
  "workflowId": "52740571-383c-45e0-b6a7-476e9434c1d2",
  "parentStepId": "26c2e502-2de6-4e9d-b06a-65ca45058cb9",
  "step": {
    "name": "mult",
    "executableName": "Exec.Multiply.exe",
    "arguments": "1 2",
    "parameters": {
      "loopCount": 3
    }
  }
}

###

Post {{Woof.api}}/runs
Content-Type: application/json

{
  "workflowId": "52740571-383c-45e0-b6a7-476e9434c1d2"
}
