@Woof.api = http://localhost:5198

GET {{Woof.api}}/definitions

###
Post {{Woof.api}}/definitions/create
Content-Type: application/json

{
  "name": "Crap"
}

###

Post {{Woof.api}}/definitions/add_next_step
Content-Type: application/json

{
  "workflowId": "eb9b37c8-e1dd-43b3-b7ed-a57375b80906",
  "parentStepId": null,
  "step": {
    "name": "mult",
    "executableName": "Exec.Multiply.exe",
    "arguments": "1 2",
    "sequentialParameters": {}
  }
}

###

Post {{Woof.api}}/definitions/add_next_step
Content-Type: application/json

{
  "workflowId": "eb9b37c8-e1dd-43b3-b7ed-a57375b80906",
  "parentStepId": "96c01ed8-7df0-4d2c-ab0d-fc67bf281d16",
  "step": {
    "name": "mult",
    "executableName": "Exec.Multiply.exe",
    "arguments": "1 2",
    "loopParameters": {
      "loopCount": 3
    }
  }
}

###

Post {{Woof.api}}/runs
Content-Type: application/json

{
  "workflowId": "eb9b37c8-e1dd-43b3-b7ed-a57375b80906"
}
